/* Independent single-instruction vectors, flat test bus. Links the REAL
 * generated byte-specific native bodies and guarded dispatcher, no CPU oracle.
 * All memory writes, final registers (including WZ/Q/P), total T-states and
 * SMS-visible I/O transactions are checked. This is not a bus waveform test. */
#include "game_banked.h"
#include "vector_state.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

Z80State g_z80;
static uint8_t memory[65536], expected_memory[65536];
static uint32_t port[3], port_count, io_count, io_error;
uint8_t sms_read8(uint16_t a) { return memory[a]; }
void sms_write8(uint16_t a, uint8_t v) { memory[a] = v; }
uint8_t sms_io_in(uint8_t p) {
    if (io_count++ || port_count != 1 || p != (uint8_t)port[0] || port[2] != 'r') io_error = 1;
    return (uint8_t)port[1];
}
void sms_io_out(uint8_t p, uint8_t v) {
    if (io_count++ || port_count != 1 || p != (uint8_t)port[0] || v != port[1] || port[2] != 'w') io_error = 1;
}
#ifdef VECTOR_REFERENCE
#include "runtime_reference.h"
static uint8_t ref_read(void *u, uint16_t a) { return sms_read8(a); }
static void ref_write(void *u, uint16_t a, uint8_t v) { sms_write8(a, v); }
static uint8_t ref_in(z80 *z, uint8_t p) { return sms_io_in(p); }
static void ref_out(z80 *z, uint8_t p, uint8_t v) { sms_io_out(p, v); }
static int reference_step(void) {
    z80 z; z80_init(&z);
    z.read_byte = ref_read; z.write_byte = ref_write; z.port_in = ref_in; z.port_out = ref_out;
#define REGISTERS(X) X(a) X(b) X(c) X(d) X(e) X(h) X(l) X(a_) X(f_) X(b_) X(c_) X(d_) X(e_) X(h_) X(l_) X(pc) X(sp) X(ix) X(iy) X(i) X(r) X(iff1) X(iff2) X(q) X(p)
#define TO_REF(n) z.n = g_z80.n;
    REGISTERS(TO_REF)
    z.mem_ptr = g_z80.wz; z.interrupt_mode = g_z80.im; z.iff_delay = g_z80.ei_block;
    uint8_t f = g_z80.f;
    z.sf = (f>>7)&1; z.zf = (f>>6)&1; z.yf = (f>>5)&1; z.hf = (f>>4)&1;
    z.xf = (f>>3)&1; z.pf = (f>>2)&1; z.nf = (f>>1)&1; z.cf = f&1;
    z80_step(&z);
#define FROM_REF(n) g_z80.n = z.n;
    REGISTERS(FROM_REF)
    g_z80.wz = z.mem_ptr; g_z80.im = z.interrupt_mode; g_z80.ei_block = z.iff_delay;
    g_z80.f = (z.sf<<7)|(z.zf<<6)|(z.yf<<5)|(z.hf<<4)|(z.xf<<3)|(z.pf<<2)|(z.nf<<1)|z.cf;
    g_z80.cyc = z.cyc;
    return 1;
}
#endif
static uint32_t word(FILE *file) {
    uint32_t v;
    if (fread(&v, 4, 1, file) != 1) { fprintf(stderr, "Truncated vectors\n"); exit(2); }
    return v;
}
static void ram(FILE *file, uint8_t *target) {
    unsigned n = word(file);
    while (n--) { uint32_t address = word(file); target[address & 65535] = (uint8_t)word(file); }
}
int main(int argc, char **argv) {
    if (argc != 2) return 2;
    FILE *file = fopen(argv[1], "rb"); if (!file) return 2;
    uint32_t count = word(file), failed = 0, misses = 0;
    for (uint32_t test = 0; test < count; ++test) {
        uint32_t initial[VECTOR_FIELDS], final[VECTOR_FIELDS], actual[VECTOR_FIELDS];
        for (unsigned i = 0; i < VECTOR_FIELDS; ++i) initial[i] = word(file);
        for (unsigned i = 0; i < VECTOR_FIELDS; ++i) final[i] = word(file);
        memset(memory, 0xA5, sizeof memory); ram(file, memory);
        memcpy(expected_memory, memory, sizeof memory); ram(file, expected_memory);
        port_count = word(file); io_count = io_error = 0;
        if (port_count > 1) return 2;
        for (unsigned i = 0; i < port_count; ++i) for (unsigned j = 0; j < 3; ++j) port[j] = word(file);
        vector_load(initial);
        /* EI's inherited delay expires after this instruction. A newly
         * emitted EI sets it again. IRQ acceptance is tested separately. */
        g_z80.ei_block = 0;
        int step;
#ifdef VECTOR_REFERENCE
        step = reference_step();
#else
        do { step = game_banked_guarded_step(); } while (step >= 3);
#endif
        if (!step) { misses++; printf("MISS %u\n", test); continue; }
        vector_save(actual);
        int different = 0;
        for (unsigned i = 0; i < VECTOR_FIELDS; ++i) if (actual[i] != final[i]) {
            printf("FAIL %u %s %u %u\n", test, vector_names[i], actual[i], final[i]); different = 1;
        }
        if (memcmp(memory, expected_memory, sizeof memory)) { printf("FAIL %u RAM\n", test); different = 1; }
        if (io_error || io_count != port_count) { printf("FAIL %u IO\n", test); different = 1; }
        failed += different;
    }
    fclose(file);
    printf("CHECKS=%u FAILED=%u MISSES=%u\n", count, failed, misses);
    return failed || misses ? 1 : 0;
}
