"""Cache independent NMOS Z80 vectors for the native release checks.

The upstream corpus is MIT licensed and generated by JSMoo, not recorded from
SMS hardware. Read a pinned archive without extracting paths from the archive.
Keep a deterministic, evenly spaced sample from every instruction family.
"""
import argparse
import hashlib
import json
from pathlib import Path
import tarfile
import urllib.request

REVISION = 'ebe1875d48f374bcfd4b505d8eb8ee751568b5f7'
ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / '.deps/z80-vectors'


def fetch(samples=32):
    CACHE.mkdir(parents=True, exist_ok=True)
    target = CACHE / f'{REVISION}-{samples}.json'
    if target.exists():
        return target
    url = f'https://codeload.github.com/SingleStepTests/z80/tar.gz/{REVISION}'
    cases, families = [], []
    with urllib.request.urlopen(url, timeout=120) as response:
        with tarfile.open(fileobj=response, mode='r|gz') as archive:
            for member in archive:
                path = Path(member.name)
                if path.name == 'LICENSE':
                    (CACHE / 'LICENSE').write_bytes(archive.extractfile(member).read())
                if path.parent.name != 'v1' or path.suffix != '.json':
                    continue
                raw = archive.extractfile(member).read()
                vectors = json.loads(raw)
                count = min(samples, len(vectors))
                for i in range(count):
                    case = vectors[i * len(vectors) // count]
                    case['family'] = path.stem
                    cases.append(case)
                families.append({'name': path.stem, 'sha256': hashlib.sha256(raw).hexdigest(),
                                 'available': len(vectors), 'selected': count})
                if len(families) % 100 == 0:
                    print(f'{len(families)} families, {len(cases)} vectors', flush=True)
    target.write_text(json.dumps({'revision': REVISION, 'source': url,
        'families': families, 'cases': cases}, separators=(',', ':')), encoding='utf-8')
    print(target, flush=True)
    return target


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--samples', type=int, default=32)
    args = parser.parse_args()
    if not 1 <= args.samples <= 1000:
        parser.error('--samples must be between 1 and 1000')
    fetch(args.samples)
